# Class variables are variables that are shared by all objects of a class.
# They are defined inside the class but outside the methods.
# Class methods are methods that work with class-level data.
# In Python, class methods are defined using the @classmethod decorator.
# The first parameter of a class method is cls, which refers to the class.

class Student:

    # Class variables
    institute = "VCube"
    std_fees = []

    def __init__(self, name, age, m1, m2, fee):
        # Instance variables
        self.name = name
        self.age = age
        self.Physics_Marks = m1
        self.Math_Marks = m2

        # Adding each student's fee to the class variable
        Student.std_fees.append(fee)

    # Instance method
    def info(self):
        return self.name, self.age

    # Instance method
    def getaverage(self):
        return (self.Physics_Marks + self.Math_Marks) // 2

    # Instance method
    def getgrade(self):
        avg = self.getaverage()

        if avg > 70:
            grade = "A+"
        elif avg > 60:
            grade = "B"
        elif avg > 50:
            grade = "C"
        else:
            grade = "D"

        # {} are placeholders used to insert values into a string.
        # .format() replaces the {} with the given values in order.

        return "{} has secured {} grade".format(self.name, grade)

    # Class method
    @classmethod
    def getrevenue(cls):
        revenue = 0

        # Accessing the class variable using cls
        for fee in cls.std_fees:
            revenue += fee

        return "{} has generated revenue of {}".format(
            cls.institute, revenue
        )


# Creating objects and passing values to the constructor
s1 = Student("BMK", 24, 46, 56, 100000)
s2 = Student("Ram", 25, 89, 90, 23000)
s3 = Student("Raj", 26, 76, 76, 1000)

# Calling the instance method using the object
result = s1.info()
print("Student information:", result)

# Calling the instance method using the object
result = s1.getgrade()
print(result)

# Calling the class method using the class
revenue = Student.getrevenue()
print(revenue)

# Class variables are shared by all instances of the class. In this example, institute and std_fees are class variables.
# Class methods are methods that work with class-level data. In this example, getrevenue() is a class method that calculates the total revenue generated by all students.